### ISSUE TITLE
Migrate project to .NET 8

### ISSUE THREAD

**Issue by NetDevForLife** [NetDevForLife/API-UploadFiles#3]

**Comment by umardevX** [comment]
your project is not running successfully on my local machine i don't why that's why last time unable to update the nuget packages.

**Comment by umardevX** [comment]
on project running it ask me to select startup item which is i'm unable to select that. If you can guide me on that i will do all stuff from scratch and create a new PR. You can also reassign me again,

**Comment by NetDevForLife** [comment]
@umardevX I updated the project version to version 8 of the .NET framework SDK, and I added the solutions file so that it is easier to open the project with Visual Studio 2022 (it requires the latest version of .NET SDK 8.0.403 (https://dotnet.microsoft.com/it-it/download/dotnet/8.0).

I tried to build and run the code from the powershell CLI, and everything works fine (I attach screenshots).

![image](https://github.com/user-attachments/assets/5de113bd-0865-46e4-a162-5da024d166ac)

Let me know if you encounter other problems, maybe adding some screenshots.

**Comment by NetDevForLife** [comment]
Updated solution reference SDK for .NET 8 and updated related Nuget packages in the commit: 71693b856587c8dbb5f379f1b7c808bbcd8918c8

**Comment by umardevX** [comment]
@NetDevForLife what next we need to do?
or migration stuff completed?

**Comment by NetDevForLife** [comment]
@umardevX this issue can be considered closed, as there is another one (issue #4) for the migration from controllers to minimal api
